# Generated by Django 4.1.7 on 2023-06-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration',
            field=models.CharField(default='a', max_length=25),
            preserve_default=False,
        ),
    ]
