# Generated by Django 4.1.7 on 2023-06-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_block_remove_classroom_block_name_classroom_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
