# Generated by Django 4.1.7 on 2023-06-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_alter_block_name_alter_classroom_block'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('block', 'name')},
        ),
    ]
